export {default as StartImage} from './Images/StartImage.png';
export {default as StartText} from './Images/StartText.png';
export {default as Eye} from './Images/eye.png';
export {default as EyeOff} from './Images/eye-off.png';
export {default as Add} from './Images/add.png';
export {default as AllergyTitle} from './Images/AllergyTitle.png';
export {default as AllergyCheckTitle} from './Images/AllergyCheckTitle.png';
export {default as Gear} from './Images/gear.png';
export {default as ProfileImg} from './Images/Profile.png';

export * from './Person';
export * from './Person_filled';
export * from './Bookmark';
export * from './Bookmark_filled';
export * from './Home';
export * from './Home_filed';
export * from './Today';
export * from './Today_filed';
export * from './Trophy';
export * from './Trophy_filed';
export * from './Access_time';
export * from './Search';
export * from './Arrow_right';
export * from './Arrow_left';
export * from './Star_filed';
export * from './File_upload';
export * from './Pencil';
export * from './More';
export * from './Arrow_back';
