export {default as StartImage} from './Images/StartImage.png';
export {default as StartText} from './Images/StartText.png';
export {default as BackArrow} from './Images/arrow_back.png';
export {default as LoginTitle} from './Images/LoginTitle.png';
export {default as Eye} from './Images/eye.png';
export {default as EyeOff} from './Images/eye-off.png';

export * from './Person';
export * from './Person_filled';
export * from './Bookmark';
export * from './Bookmark_filled';
export * from './Home';
export * from './Home_filed';
export * from './Today';
export * from './Today_filed';
export * from './Trophy';
export * from './Trophy_filed';
export * from './Access_time';
export * from './Search';
export * from './Arrow_right';
